{{- if .Values.kafkaUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}-kafka-ui
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
spec:
  type: {{ .Values.kafkaUi.service.type }}
  ports:
    - port: {{ .Values.kafkaUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flask-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
{{- end }}

