apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  labels:
    app.kubernetes.io/instance: team7-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: team7-app
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: team7-app
  name: team7-app
  namespace: demo
spec:
  ingressClassName: nginx
  rules:
    - host: demo.kubepractice.ru
      http:
        paths:
          - backend:
              service:
                name: team7-app
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - demo.kubepractice.ru
      secretName: tls-secret
