{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "team7-helm.fullname" . }}-ingress
  labels:
    {{- include "team7-helm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.tls .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.coreService.enabled }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "team7-helm.fullname" . }}-core-service
                port:
                  number: {{ .Values.coreService.service.port }}
          {{- end }}
          {{- if .Values.trainService.enabled }}
          - path: /train
            pathType: Prefix
            backend:
              service:
                name: {{ include "team7-helm.fullname" . }}-train-service
                port:
                  number: {{ .Values.trainService.service.port }}
          {{- end }}
          {{- if .Values.artifactsService.enabled }}
          - path: /artifacts
            pathType: Prefix
            backend:
              service:
                name: {{ include "team7-helm.fullname" . }}-artifacts-service
                port:
                  number: {{ .Values.artifactsService.service.port }}
          {{- end }}
          {{- if .Values.coreServiceFrontend.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "team7-helm.fullname" . }}-core-service-frontend
                port:
                  number: {{ .Values.coreServiceFrontend.service.port }}
          {{- end }}
          {{- if .Values.coreService.enabled }}
          - path: /datasets
            pathType: Prefix
            backend:
              service:
                name: {{ include "team7-helm.fullname" . }}-artifacts-service
                port:
                  number: {{ .Values.artifactsService.service.port }}
          {{- end }}
          {{- if .Values.kafka.enabled }}
          - path: /kafka-brokers
            pathType: Prefix
            backend:
              service:
                name: {{ include "team7-helm.fullname" . }}-kafka-kafka-bootstrap
                port:
                  number: {{ .Values.kafka.service.port }}
            {{- end }}
{{- end }}
