apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  labels:
    app.kubernetes.io/instance: {{ include "flask-app.fullname" . }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ include "flask-app.name" . }}
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: {{ include "flask-app.chart" . }}
  name: {{ include "flask-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: {{ include "flask-app.fullname" . }}
                port:
                  number: 5000
          - path: /kafka/status
            pathType: Prefix
            backend:
              service:
                name: {{ include "flask-app.fullname" . }}
                port:
                  number: 5000

  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: tls-secret
